// Created by BBMW0 Technologies | bbmw0.com
/**
 * ENGAGEMENT AGENT: Community Response System
 *
 * Deploys rotating NEUROMESH agents to reply to comments and reviews across
 * all channels. Every reply is generated by Claude, sanitised for UK English,
 * and checked for banned characters before posting via Composio.
 *
 * Platforms covered:
 *   YouTube Main    (@bbmw.0)          - comments on all videos
 *   YouTube Games   (@BBMW0 Games)     - comments on game videos
 *   Instagram       (@ai_game_odyssey) - comments on all posts
 *   Google Play     (all published apps) - review replies
 *
 * Language policy:
 *   - All English responses use United Kingdom English spelling and grammar
 *   - If a comment is written in a language other than English, the reply is
 *     in that same language (auto-detected by Claude)
 *   - Em dashes (U+2014), smart quotes, and non-standard Unicode are stripped
 *
 * Agent rotation:
 *   Personas cycle across the NEUROMESH pool so replies look organic.
 *   Games channel uses Pixel/Forge personas. Main/IG use growth/content agents.
 *
 * Engagement log:
 *   results/engagement-log.json tracks every replied comment ID so the agent
 *   never double-replies.
 */

import * as fs   from "fs";
import * as path from "path";
import Anthropic  from "@anthropic-ai/sdk";
import { agentSecurity }                    from "../security/agent-security-engine";
import { alertInfo, alertWarning }          from "./email-notifier";
import { COMPOSIO_ACCOUNTS }                from "./composio-publisher";
import { executeComposioAction, executeComposioPlan, ComposioExecutionError } from "./composio-executor";

// ── CONSTANTS ─────────────────────────────────────────────────────────────────

const ENGAGEMENT_LOG_PATH = path.join(__dirname, "../../results/engagement-log.json");

// Max replies per platform per run to stay within API quotas
const MAX_REPLIES_PER_PLATFORM: Record<string, number> = {
  youtube_main:  30,
  youtube_games: 30,
  instagram:     20,
  google_play:   20,
};

// ── AGENT PERSONAS FOR ENGAGEMENT ─────────────────────────────────────────────

interface EngagementPersona {
  id:       string;
  name:     string;
  platform: "youtube_main" | "youtube_games" | "instagram" | "google_play" | "all";
  tone:     string;
}

const ENGAGEMENT_PERSONAS: EngagementPersona[] = [
  // Main YouTube channel (video editing, AI, tech)
  { id: "AG-003", name: "Aurora",   platform: "youtube_main",  tone: "warm, encouraging, talks like a senior content creator who has been through the journey" },
  { id: "AG-007", name: "Nova",     platform: "youtube_main",  tone: "energetic, punchy, celebrates community wins and drops quick growth tips" },
  { id: "AG-006", name: "Velocity", platform: "youtube_main",  tone: "direct, results-focused, answers technical questions with clear steps" },
  { id: "AG-004", name: "Lyric",    platform: "youtube_main",  tone: "creative, uses vivid language, great at hyping up someone's progress" },

  // Games channel
  { id: "AG-012", name: "Forge",    platform: "youtube_games", tone: "passionate game developer, loves talking about AI-built games, answers dev questions enthusiastically" },
  { id: "AG-013", name: "Pixel",    platform: "youtube_games", tone: "gamer energy, hype about new releases, keeps it fun and technical" },
  { id: "AG-019", name: "Oracle",   platform: "youtube_games", tone: "data-driven, drops interesting facts about game mechanics and AI tech behind each game" },

  // Instagram
  { id: "AG-005", name: "Prism",    platform: "instagram",     tone: "visually descriptive, Instagram-native energy, celebrates aesthetics and results" },
  { id: "AG-007", name: "Nova",     platform: "instagram",     tone: "short punchy replies, heavy use of affirmation, community builder" },
  { id: "AG-020", name: "Scout",    platform: "instagram",     tone: "curious and engaging, asks follow-up questions to drive conversation" },

  // Google Play reviews
  { id: "AG-012", name: "Forge",    platform: "google_play",   tone: "professional yet personable dev voice, takes feedback seriously, thanks players for input" },
  { id: "AG-013", name: "Pixel",    platform: "google_play",   tone: "appreciative and responsive, addresses specific points in the review" },

  // Fallback for any platform
  { id: "AG-006", name: "Velocity", platform: "all",           tone: "clear, helpful, gets straight to the point" },
];

// ── ENGAGEMENT LOG ─────────────────────────────────────────────────────────────

interface EngagementLogEntry {
  platform:     string;
  commentId:    string;
  repliedAt:    string;
  agentId:      string;
  replyPreview: string;
}

function loadEngagementLog(): EngagementLogEntry[] {
  if (!fs.existsSync(ENGAGEMENT_LOG_PATH)) return [];
  try {
    return JSON.parse(fs.readFileSync(ENGAGEMENT_LOG_PATH, "utf8")) as EngagementLogEntry[];
  } catch {
    return [];
  }
}

function saveEngagementLog(entries: EngagementLogEntry[]): void {
  fs.mkdirSync(path.dirname(ENGAGEMENT_LOG_PATH), { recursive: true });
  fs.writeFileSync(ENGAGEMENT_LOG_PATH, JSON.stringify(entries, null, 2));
}

function hasAlreadyReplied(commentId: string, platform: string, log: EngagementLogEntry[]): boolean {
  return log.some(e => e.commentId === commentId && e.platform === platform);
}

function recordReply(
  commentId: string,
  platform: string,
  agentId: string,
  replyText: string,
  log: EngagementLogEntry[]
): EngagementLogEntry[] {
  const entry: EngagementLogEntry = {
    platform,
    commentId,
    repliedAt:    new Date().toISOString(),
    agentId,
    replyPreview: replyText.slice(0, 120),
  };
  const updated = [...log, entry];
  saveEngagementLog(updated);
  return updated;
}

// ── TEXT SANITISATION ─────────────────────────────────────────────────────────

/**
 * Strips em dashes, smart quotes, non-breaking spaces, and other irregular
 * Unicode that looks wrong on platform notifications or when copy-pasted.
 * Replaces em dashes with a simple hyphen-space pattern.
 * Converts smart quotes to straight quotes.
 */
function sanitiseReply(text: string): string {
  return text
    .replace(/ - /g, " - ")          // em dash -> spaced hyphen
    .replace(/–/g, " - ")          // en dash -> spaced hyphen
    .replace(/‘|’/g, "'")     // smart single quotes -> straight
    .replace(/“|”/g, '"')     // smart double quotes -> straight
    .replace(/ /g, " ")            // non-breaking space -> regular space
    .replace(/…/g, "...")          // ellipsis char -> three dots
    .replace(/[^\x00-\x7FÀ-ɏЀ-ӿ؀-ۿ一-鿿぀-ゟ゠-ヿ가-힯]/g, "")
    .replace(/  +/g, " ")              // collapse multiple spaces
    .trim();
}

// ── LANGUAGE DETECTION (lightweight heuristic) ────────────────────────────────

function detectScriptFamily(text: string): string {
  if (/[一-鿿぀-ヿ]/.test(text)) return "CJK";
  if (/[가-힯]/.test(text))               return "Korean";
  if (/[Ѐ-ӿ]/.test(text))               return "Cyrillic";
  if (/[؀-ۿ]/.test(text))               return "Arabic";
  if (/[ऀ-ॿ]/.test(text))               return "Devanagari";
  return "Latin";
}

// ── CLAUDE REPLY GENERATOR ─────────────────────────────────────────────────────

interface CommentContext {
  platform:        string;
  channelName:     string;
  videoOrPostTitle?: string;
  commentAuthor:   string;
  commentText:     string;
  commentRating?:  number;  // 1-5, for Play Store reviews
  persona:         EngagementPersona;
}

async function generateReply(client: Anthropic, ctx: CommentContext): Promise<string> {
  const scriptFamily = detectScriptFamily(ctx.commentText);
  const languageInstruction =
    scriptFamily === "Latin"
      ? "The reply must be in United Kingdom English. Use UK spelling throughout (colour, optimise, recognise, favour, behaviour, whilst, amongst, etc.). Do NOT use American spellings."
      : `The comment appears to be in a non-Latin script (${scriptFamily}). Reply in the same language as the comment. If you include any English words, use UK spelling.`;

  const platformContext =
    ctx.platform === "google_play"
      ? `This is a Google Play Store review (${ctx.commentRating ?? "??"}/5 stars) for the app "${ctx.channelName}".`
      : `This is a comment on ${ctx.platform === "youtube_main" || ctx.platform === "youtube_games" ? "YouTube" : "Instagram"} for ${ctx.channelName}.`;

  const videoContext = ctx.videoOrPostTitle
    ? ` The comment is on the post/video: "${ctx.videoOrPostTitle}".`
    : "";

  const system = [
    `You are ${ctx.persona.name}, a NEUROMESH AI agent from BBMW0 Technologies.`,
    `Your engagement tone: ${ctx.persona.tone}.`,
    "",
    `${platformContext}${videoContext}`,
    "",
    "STRICT RULES:",
    "1. " + languageInstruction,
    "2. NEVER use em dashes (the long dash character: -). Use a simple hyphen or rewrite the sentence instead.",
    "3. NEVER use smart/curly quotes. Use straight apostrophes and quotes only.",
    "4. Keep replies concise: 1-3 sentences for YouTube/Instagram, up to 5 sentences for Play Store reviews.",
    "5. Be genuine and specific - reference something from the actual comment.",
    "6. Do NOT copy the comment back verbatim.",
    "7. Do NOT use excessive exclamation marks (max 1 per reply).",
    "8. Do NOT sign off with your name or any sign-off text.",
    "9. Do NOT use hashtags in replies.",
    "10. For negative reviews or complaints, acknowledge the issue, apologise briefly, and offer to help.",
    "11. Output ONLY the reply text. No preamble, no labels, no explanation.",
  ].join("\n");

  const response = await client.messages.create({
    model:      "claude-haiku-4-5-20251001",
    max_tokens: 300,
    system,
    messages: [
      {
        role:    "user",
        content: `Comment from @${ctx.commentAuthor}: "${ctx.commentText}"`,
      },
    ],
  });

  const raw = response.content[0].type === "text" ? response.content[0].text.trim() : "";
  return sanitiseReply(raw);
}

// ── COMPOSIO TOOL PLANS ────────────────────────────────────────────────────────

function buildYouTubeReplyPlan(videoId: string, parentCommentId: string, replyText: string, accountId: string): object[] {
  return [
    {
      tool:   "YOUTUBE_COMMENTS_INSERT",
      params: {
        part:               "snippet",
        requestBody: {
          snippet: {
            parentId:    parentCommentId,
            textOriginal: replyText,
          },
        },
        accountId,
      },
    },
  ];
}

function buildInstagramReplyPlan(mediaId: string, commentId: string, replyText: string): object[] {
  return [
    {
      tool:   "INSTAGRAM_CREATE_REPLY_TO_COMMENT",
      params: {
        ig_user_id:  COMPOSIO_ACCOUNTS.instagram.igUserId,
        comment_id:  commentId,
        message:     replyText,
      },
    },
  ];
}

function buildGooglePlayReplyPlan(packageName: string, reviewId: string, replyText: string): object[] {
  return [
    {
      tool:   "GOOGLEPLAY_REVIEWS_REPLY",
      params: {
        packageName,
        reviewId,
        requestBody: {
          replyText,
        },
      },
    },
  ];
}

function buildYouTubeFetchCommentsPlan(videoId: string, accountId: string): object[] {
  return [
    {
      tool:   "YOUTUBE_COMMENT_THREADS_LIST",
      params: {
        part:       "snippet",
        videoId,
        maxResults: 50,
        order:      "relevance",
        accountId,
      },
    },
  ];
}

function buildInstagramFetchCommentsPlan(mediaId: string): object[] {
  return [
    {
      tool:   "INSTAGRAM_GET_IG_MEDIA_COMMENTS",
      params: {
        ig_user_id: COMPOSIO_ACCOUNTS.instagram.igUserId,
        media_id:   mediaId,
        fields:     "id,text,username,timestamp",
      },
    },
  ];
}

function buildGooglePlayFetchReviewsPlan(packageName: string): object[] {
  return [
    {
      tool:   "GOOGLEPLAY_REVIEWS_LIST",
      params: {
        packageName,
        maxResults: 50,
        translationLanguage: "en_GB",
      },
    },
  ];
}

// ── PERSONA ROTATION ───────────────────────────────────────────────────────────

function selectPersona(
  platform: EngagementPersona["platform"],
  seed: number
): EngagementPersona {
  const pool = ENGAGEMENT_PERSONAS.filter(p => p.platform === platform || p.platform === "all");
  return pool[seed % pool.length];
}

// ── ENGAGEMENT RESULT ──────────────────────────────────────────────────────────

export interface EngagementRunResult {
  runId:          string;
  startedAt:      string;
  completedAt:    string;
  totalComments:  number;
  totalReplied:   number;
  totalSkipped:   number;
  byPlatform:     Record<string, { replied: number; skipped: number }>;
  errors:         string[];
}

// ── MAIN ENGAGEMENT AGENT ─────────────────────────────────────────────────────

export class EngagementAgent {
  private anthropic: Anthropic;

  constructor() {
    this.anthropic = new Anthropic();
  }

  /**
   * Main daily sweep. Called from AutonomousPublisher.runDailyCycle().
   * Processes comments and reviews across all platforms.
   *
   * videoIds and mediaIds come from the upload log: the autonomous publisher
   * records every published post ID, so we know which content to check.
   * For Google Play, appPackageNames lists all published app IDs.
   */
  async runDailySweep(options: {
    youtubeMainVideoIds:   string[];
    youtubeGamesVideoIds:  string[];
    instagramMediaIds:     string[];
    googlePlayPackages:    string[];
  }): Promise<EngagementRunResult> {
    const runId    = `engage-${Date.now()}`;
    const start    = new Date().toISOString();
    let log        = loadEngagementLog();
    let seed       = Math.floor(Date.now() / 3_600_000); // changes each hour

    const result: EngagementRunResult = {
      runId,
      startedAt:     start,
      completedAt:   "",
      totalComments: 0,
      totalReplied:  0,
      totalSkipped:  0,
      byPlatform:    {
        youtube_main:  { replied: 0, skipped: 0 },
        youtube_games: { replied: 0, skipped: 0 },
        instagram:     { replied: 0, skipped: 0 },
        google_play:   { replied: 0, skipped: 0 },
      },
      errors: [],
    };

    const ctx = {
      agentId:   "engagement-agent",
      tenantId:  "bbmw0-main",
      operation: "reply-to-comments",
      timestamp: new Date().toISOString(),
    };
    agentSecurity.runFullSecurityAudit(ctx);

    console.log(`[Engagement] Daily sweep started: ${runId}`);

    // ── YouTube Main ──────────────────────────────────────────────────────────
    for (const videoId of options.youtubeMainVideoIds) {
      if (result.byPlatform.youtube_main.replied >= MAX_REPLIES_PER_PLATFORM.youtube_main) break;
      try {
        const comments = await this.fetchYouTubeComments(videoId, COMPOSIO_ACCOUNTS.youtube.accountId);
        for (const comment of comments) {
          if (hasAlreadyReplied(comment.id, "youtube_main", log)) {
            result.byPlatform.youtube_main.skipped++;
            continue;
          }
          result.totalComments++;
          const persona = selectPersona("youtube_main", seed++);
          const reply   = await generateReply(this.anthropic, {
            platform:        "youtube_main",
            channelName:     "BBMW0 - Video Editing, AI and Tech",
            videoOrPostTitle: comment.videoTitle,
            commentAuthor:   comment.author,
            commentText:     comment.text,
            persona,
          });
          const plan = buildYouTubeReplyPlan(videoId, comment.id, reply, COMPOSIO_ACCOUNTS.youtube.accountId);
          await this.executeComposioReply("youtube_main", comment.id, plan, reply, COMPOSIO_ACCOUNTS.youtube.accountId);
          log = recordReply(comment.id, "youtube_main", persona.id, reply, log);
          result.totalReplied++;
          result.byPlatform.youtube_main.replied++;
        }
      } catch (err: unknown) {
        const msg = `YouTube Main comment fetch failed for ${videoId}: ${String(err)}`;
        result.errors.push(msg);
        console.error(`[Engagement] ${msg}`);
      }
    }

    // ── YouTube Games ─────────────────────────────────────────────────────────
    for (const videoId of options.youtubeGamesVideoIds) {
      if (result.byPlatform.youtube_games.replied >= MAX_REPLIES_PER_PLATFORM.youtube_games) break;
      try {
        const comments = await this.fetchYouTubeComments(videoId, COMPOSIO_ACCOUNTS.youtubeGames.accountId);
        for (const comment of comments) {
          if (hasAlreadyReplied(comment.id, "youtube_games", log)) {
            result.byPlatform.youtube_games.skipped++;
            continue;
          }
          result.totalComments++;
          const persona = selectPersona("youtube_games", seed++);
          const reply   = await generateReply(this.anthropic, {
            platform:        "youtube_games",
            channelName:     "BBMW0 Games",
            videoOrPostTitle: comment.videoTitle,
            commentAuthor:   comment.author,
            commentText:     comment.text,
            persona,
          });
          const plan = buildYouTubeReplyPlan(videoId, comment.id, reply, COMPOSIO_ACCOUNTS.youtubeGames.accountId);
          await this.executeComposioReply("youtube_games", comment.id, plan, reply, COMPOSIO_ACCOUNTS.youtubeGames.accountId);
          log = recordReply(comment.id, "youtube_games", persona.id, reply, log);
          result.totalReplied++;
          result.byPlatform.youtube_games.replied++;
        }
      } catch (err: unknown) {
        const msg = `YouTube Games comment fetch failed for ${videoId}: ${String(err)}`;
        result.errors.push(msg);
        console.error(`[Engagement] ${msg}`);
      }
    }

    // ── Instagram ─────────────────────────────────────────────────────────────
    for (const mediaId of options.instagramMediaIds) {
      if (result.byPlatform.instagram.replied >= MAX_REPLIES_PER_PLATFORM.instagram) break;
      try {
        const comments = await this.fetchInstagramComments(mediaId);
        for (const comment of comments) {
          if (hasAlreadyReplied(comment.id, "instagram", log)) {
            result.byPlatform.instagram.skipped++;
            continue;
          }
          result.totalComments++;
          const persona = selectPersona("instagram", seed++);
          const reply   = await generateReply(this.anthropic, {
            platform:      "instagram",
            channelName:   "@ai_game_odyssey",
            commentAuthor: comment.author,
            commentText:   comment.text,
            persona,
          });
          const plan = buildInstagramReplyPlan(mediaId, comment.id, reply);
          await this.executeComposioReply("instagram", comment.id, plan, reply, COMPOSIO_ACCOUNTS.instagram.accountId);
          log = recordReply(comment.id, "instagram", persona.id, reply, log);
          result.totalReplied++;
          result.byPlatform.instagram.replied++;
        }
      } catch (err: unknown) {
        const msg = `Instagram comment fetch failed for ${mediaId}: ${String(err)}`;
        result.errors.push(msg);
        console.error(`[Engagement] ${msg}`);
      }
    }

    // ── Google Play Reviews ───────────────────────────────────────────────────
    for (const packageName of options.googlePlayPackages) {
      if (result.byPlatform.google_play.replied >= MAX_REPLIES_PER_PLATFORM.google_play) break;
      try {
        const reviews = await this.fetchGooglePlayReviews(packageName);
        for (const review of reviews) {
          if (hasAlreadyReplied(review.id, "google_play", log)) {
            result.byPlatform.google_play.skipped++;
            continue;
          }
          result.totalComments++;
          const persona = selectPersona("google_play", seed++);
          const reply   = await generateReply(this.anthropic, {
            platform:      "google_play",
            channelName:   packageName,
            commentAuthor: review.author,
            commentText:   review.text,
            commentRating: review.rating,
            persona,
          });
          const plan = buildGooglePlayReplyPlan(packageName, review.id, reply);
          await this.executeComposioReply("google_play", review.id, plan, reply, "google_play_default");
          log = recordReply(review.id, "google_play", persona.id, reply, log);
          result.totalReplied++;
          result.byPlatform.google_play.replied++;
        }
      } catch (err: unknown) {
        const msg = `Google Play review fetch failed for ${packageName}: ${String(err)}`;
        result.errors.push(msg);
        console.error(`[Engagement] ${msg}`);
      }
    }

    result.completedAt = new Date().toISOString();
    result.totalSkipped = Object.values(result.byPlatform).reduce((s, p) => s + p.skipped, 0);

    console.log(
      `[Engagement] Sweep complete. Replied: ${result.totalReplied}, Skipped: ${result.totalSkipped}`
    );

    if (result.totalReplied > 0) {
      await alertInfo(
        `Engagement sweep: ${result.totalReplied} replies sent`,
        [
          `YouTube Main:  ${result.byPlatform.youtube_main.replied} replies`,
          `YouTube Games: ${result.byPlatform.youtube_games.replied} replies`,
          `Instagram:     ${result.byPlatform.instagram.replied} replies`,
          `Google Play:   ${result.byPlatform.google_play.replied} replies`,
        ].join("\n"),
        { runId, errors: result.errors }
      );
    }

    if (result.errors.length > 0) {
      await alertWarning(
        `Engagement sweep had ${result.errors.length} error(s)`,
        result.errors.join("\n")
      );
    }

    return result;
  }

  // ── PLATFORM FETCHERS (return normalised comment shapes) ───────────────────

  private async fetchYouTubeComments(videoId: string, accountId: string): Promise<NormalisedComment[]> {
    try {
      const result = await executeComposioAction(
        "YOUTUBE_COMMENT_THREADS_LIST",
        { part: "snippet", videoId, maxResults: 50, order: "relevance", accountId },
      ) as { items?: ComposioYTCommentThread[] };

      return (result.items ?? []).map(item => ({
        id:         item.snippet.topLevelComment.id,
        author:     item.snippet.topLevelComment.snippet.authorDisplayName,
        text:       item.snippet.topLevelComment.snippet.textOriginal,
        videoTitle: item.snippet.videoId,
        repliedTo:  !!item.replies?.comments?.length,
      }));
    } catch (err) {
      if (err instanceof ComposioExecutionError) {
        const msg = String(err.cause);
        if (msg.includes("403") || msg.includes("quota") || msg.includes("forbidden")) {
          console.warn(`[Engagement] YouTube comments: quota/permissions issue for ${videoId}`);
          return [];
        }
      }
      throw err;
    }
  }

  private async fetchInstagramComments(mediaId: string): Promise<NormalisedComment[]> {
    try {
      const result = await executeComposioAction(
        "INSTAGRAM_GET_IG_MEDIA_COMMENTS",
        {
          ig_user_id: COMPOSIO_ACCOUNTS.instagram.igUserId,
          media_id:   mediaId,
          fields:     "id,text,username,timestamp",
        },
      ) as { data?: ComposioIGComment[] };

      return (result.data ?? []).map(c => ({
        id:     c.id,
        author: c.username,
        text:   c.text,
      }));
    } catch (err) {
      if (err instanceof ComposioExecutionError) {
        const msg = String(err.cause);
        if (msg.includes("400") || msg.includes("not accessible") || msg.includes("invalid")) {
          console.warn(`[Engagement] Instagram comments: media ${mediaId} not accessible`);
          return [];
        }
      }
      throw err;
    }
  }

  private async fetchGooglePlayReviews(packageName: string): Promise<NormalisedReview[]> {
    try {
      const result = await executeComposioAction(
        "GOOGLEPLAY_REVIEWS_LIST",
        { packageName, maxResults: 50, translationLanguage: "en_GB" },
        "google_play_default",
      ) as { reviews?: ComposioPlayReview[] };

      return (result.reviews ?? [])
        .filter(r => !r.developerComment)
        .map(r => ({
          id:     r.reviewId,
          author: r.authorName,
          text:   r.comments[0]?.userComment?.text ?? "",
          rating: r.comments[0]?.userComment?.starRating ?? 3,
        }));
    } catch (err) {
      if (err instanceof ComposioExecutionError) {
        console.warn(`[Engagement] Play reviews: could not fetch for ${packageName}:`, err.message);
        return [];
      }
      throw err;
    }
  }

  // ── COMPOSIO REPLY DISPATCHER ────────────────────────────────────────────

  private async executeComposioReply(
    platform: string,
    commentId: string,
    plan: ReturnType<typeof buildYouTubeReplyPlan> | ReturnType<typeof buildInstagramReplyPlan> | ReturnType<typeof buildGooglePlayReplyPlan>,
    reply: string,
    accountId: string,
  ): Promise<void> {
    console.log(`[Engagement] REPLY -> ${platform} | comment:${commentId} | "${reply.slice(0, 80)}..."`);
    try {
      await executeComposioPlan(
        plan.map(s => ({
          tool:    (s as { tool: string }).tool,
          params:  (s as { params: Record<string, unknown> }).params,
        })),
        accountId,
      );
    } catch (err) {
      console.error(`[Engagement] Reply dispatch failed for ${platform}/${commentId}:`, String(err));
      throw err;
    }
  }
}

// ── NORMALISED TYPES ───────────────────────────────────────────────────────────

interface NormalisedComment {
  id:          string;
  author:      string;
  text:        string;
  videoTitle?: string;
  repliedTo?:  boolean;
}

interface NormalisedReview {
  id:     string;
  author: string;
  text:   string;
  rating: number;
}

// ── COMPOSIO API RESPONSE SHAPES ──────────────────────────────────────────────

interface ComposioYTCommentThread {
  snippet: {
    videoId: string;
    topLevelComment: {
      id: string;
      snippet: {
        authorDisplayName: string;
        textOriginal:      string;
      };
    };
  };
  replies?: { comments: unknown[] };
}

interface ComposioIGComment {
  id:        string;
  text:      string;
  username:  string;
  timestamp: string;
}

interface ComposioPlayReview {
  reviewId:         string;
  authorName:       string;
  developerComment?: unknown;
  comments: Array<{
    userComment?: {
      text:        string;
      starRating:  number;
    };
  }>;
}

export const engagementAgent = new EngagementAgent();
export default engagementAgent;
