// Created by BBMW0 Technologies | bbmw0.com
/**
 * NANO BANANA ENGINE™
 *
 * The content uniqueness and enhancement layer for OmniOrg.
 * Every video and post generated by the system passes through
 * this engine to guarantee:
 *
 *  1. CONTENT DNA FINGERPRINTING
 *     Each piece gets a unique 5-axis fingerprint:
 *     hookArchetype × visualStyle × narrativeArc × tone × energy
 *     No two pieces share the same DNA. Ever.
 *
 *  2. SIMILARITY ENFORCEMENT
 *     Before generation, the engine checks the full content
 *     library. If the proposed content is too similar to any
 *     recent piece (similarity score > 0.6), it rotates axes
 *     automatically until a novel combination is found.
 *
 *  3. ENHANCEMENT RECIPES
 *     12 pre-tuned recipes, each optimised for a different
 *     goal: virality, authority, engagement, trust, reach.
 *     Each recipe maps to a specific axis combination + a set
 *     of production directives.
 *
 *  4. VARIATION INJECTION
 *     Rewrites hooks, thumbnails, CTAs, and edit styles to
 *     maximise variety across a content calendar — even when
 *     topics overlap.
 *
 *  5. CROSS-PLATFORM DIFFERENTIATION
 *     The same topic on Instagram vs YouTube gets completely
 *     different treatment: angle, structure, energy, format.
 */

import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

// ── DNA AXES ──────────────────────────────────────────────────────────────────

export const HOOK_ARCHETYPES = [
  "curiosity-gap",       // "Nobody tells you this about..."
  "bold-claim",          // "This changed everything for me..."
  "story-start",         // "3 months ago I was..."
  "direct-question",     // "Are you making this mistake?"
  "shock-stat",          // "90% of people get this wrong..."
  "transformation",      // "I went from X to Y by doing..."
  "challenge",           // "Try this for 7 days and tell me..."
  "confession",          // "I'm going to be honest with you..."
  "tutorial-preview",    // "In this video I'll show you exactly..."
  "controversial-take",  // "Everyone says X. They're wrong."
  "social-proof",        // "I've taught 10,000 people to..."
  "fomo",                // "Before you post another video, watch this"
] as const;

export const VISUAL_STYLES = [
  "cinematic",            // Slow push-ins, b-roll heavy, filmic grade
  "clean-minimal",        // White/light bg, precise typography, calm pacing
  "energetic-fast-cut",   // Sub-1s cuts, zoom punches, high energy
  "documentary",          // Long takes, ambient audio, handheld feel
  "vlog-style",           // Conversational, imperfect, authentic
  "screen-dominant",      // Screen recording fills 80%+, face in corner
  "animation-driven",     // Motion graphics, kinetic text, illustrated
  "talking-head-raw",     // Straight to camera, minimal editing, trust-first
] as const;

export const NARRATIVE_ARCS = [
  "problem-solution",    // Here's the problem → here's the fix
  "transformation",      // Before state → journey → after state
  "revelation",          // Set up mystery → reveal → implications
  "step-by-step",        // Numbered tutorial, methodical progress
  "case-study",          // Real data → what happened → what to replicate
  "debate-contrast",     // Wrong way vs right way, A vs B comparison
] as const;

export const TONES = [
  "educational-warm",    // Teacher who cares, patient, encouraging
  "entertaining-fast",   // High energy, jokes, memes, pop culture refs
  "authoritative",       // Expert, confident, data-led
  "vulnerable-personal", // Honest failures shared, raw emotion
  "hype",                // Hype man energy, excited, motivational
  "calm-expert",         // Quiet confidence, no fluff, respect your time
] as const;

export const ENERGY_LEVELS = [
  "explosive",   // Maximum intensity from frame 1
  "high",        // Consistently fast, punchy
  "medium",      // Balanced pace, engaging
  "calm",        // Deliberate, thoughtful, unhurried
  "reflective",  // Introspective, slower, emotional resonance
] as const;

export type HookArchetype  = typeof HOOK_ARCHETYPES[number];
export type VisualStyle    = typeof VISUAL_STYLES[number];
export type NarrativeArc   = typeof NARRATIVE_ARCS[number];
export type Tone           = typeof TONES[number];
export type EnergyLevel    = typeof ENERGY_LEVELS[number];

// ── CONTENT DNA ────────────────────────────────────────────────────────────────

export interface ContentDNA {
  fingerprint:    string;           // Unique hash of all 5 axes
  hookArchetype:  HookArchetype;
  visualStyle:    VisualStyle;
  narrativeArc:   NarrativeArc;
  tone:           Tone;
  energy:         EnergyLevel;
  recipeUsed:     string;
  noveltyScore:   number;           // 0-1: how different from recent content
  generatedAt:    string;
  contentId:      string;
  platform:       "instagram" | "youtube" | "both";
  topic:          string;
}

// ── ENHANCEMENT RECIPES ────────────────────────────────────────────────────────

export interface EnhancementRecipe {
  id:                string;
  name:              string;
  goal:              string;
  hookArchetype:     HookArchetype;
  visualStyle:       VisualStyle;
  narrativeArc:      NarrativeArc;
  tone:              Tone;
  energy:            EnergyLevel;
  productionNotes:   string;
  thumbnailFormula:  string;
  ctaFormula:        string;
  editingDirectives: string[];
  platformFit:       Array<"instagram" | "youtube">;
}

const ENHANCEMENT_RECIPES: EnhancementRecipe[] = [
  {
    id:              "viral-reel",
    name:            "Viral Reel Machine",
    goal:            "Maximum algorithmic reach on Instagram Reels",
    hookArchetype:   "curiosity-gap",
    visualStyle:     "energetic-fast-cut",
    narrativeArc:    "revelation",
    tone:            "entertaining-fast",
    energy:          "explosive",
    productionNotes: "Hook in first frame — no intro, no title card. Cut every 0.8-1.2 seconds. Zoom punch on key words. Captions always on. End with a cliff-hanger that makes them follow for part 2.",
    thumbnailFormula:"Bold text on high-contrast background. Creator face showing shock/surprise. Arrow pointing to key element. No more than 4 words.",
    ctaFormula:      "Drop a 🍌 in the comments if this helped you",
    editingDirectives: [
      "No music intro — beat drop into content",
      "Use viral audio trending this week from Instagram Reels library",
      "Text pop-in on every key point",
      "Zoom in 120% on the most surprising moment",
      "Black frame for 2 frames before the reveal",
    ],
    platformFit: ["instagram"],
  },
  {
    id:              "authority-builder",
    name:            "Authority Builder",
    goal:            "Establish expertise and grow a loyal following",
    hookArchetype:   "bold-claim",
    visualStyle:     "clean-minimal",
    narrativeArc:    "step-by-step",
    tone:            "authoritative",
    energy:          "medium",
    productionNotes: "Clean setup, professional lighting. Data and specifics drive trust. On-screen stats and sources. No fluff — respect viewer's time above all.",
    thumbnailFormula:"Creator in authoritative pose. Key insight as headline. Dark background with accent colour. No emojis.",
    ctaFormula:      "Subscribe for one practical tip every week — no filler",
    editingDirectives: [
      "Jump cuts to remove all pauses",
      "Lower-third text for key stats",
      "Chapter cards on-screen at each section transition",
      "Background music at -22dB max — barely audible",
      "End screen: playlist of related authority content",
    ],
    platformFit: ["youtube"],
  },
  {
    id:              "story-trust",
    name:            "Story Trust Builder",
    goal:            "Build parasocial connection through authentic storytelling",
    hookArchetype:   "story-start",
    visualStyle:     "vlog-style",
    narrativeArc:    "transformation",
    tone:            "vulnerable-personal",
    energy:          "medium",
    productionNotes: "Show the messy middle, not just the highlight reel. Real failures shared = massive trust. Handheld camera acceptable. Imperfect is authentic.",
    thumbnailFormula:"Creator in candid, unposed moment. Honest expression. Text captures the emotional truth. No stock imagery.",
    ctaFormula:      "If you've been through something similar, I'd love to hear your story in the comments",
    editingDirectives: [
      "Keep stumbles and self-corrections — they build authenticity",
      "Natural background audio under VO",
      "Split into chapters: 'The Problem' → 'What I Tried' → 'What Actually Worked'",
      "Include at least one 'I got this wrong' moment",
      "End with a reflective pause before CTA",
    ],
    platformFit: ["youtube", "instagram"],
  },
  {
    id:              "fast-tutorial",
    name:            "60-Second Tutorial",
    goal:            "High save rate and shares on Instagram",
    hookArchetype:   "tutorial-preview",
    visualStyle:     "screen-dominant",
    narrativeArc:    "step-by-step",
    tone:            "calm-expert",
    energy:          "high",
    productionNotes: "Screen fills frame. Steps numbered clearly. No wasted seconds. Every 3 steps = one save moment. End with the complete result.",
    thumbnailFormula:"Before/after split screen. Step numbers overlaid. Tool name if applicable.",
    ctaFormula:      "Save this — you'll need it later",
    editingDirectives: [
      "Screen recording at 60fps for smooth cursor movement",
      "Step numbers pop-in as each step begins",
      "Speed ramp: slow on key actions, fast on transitions",
      "Cursor highlight effect on click actions",
      "Summary overlay on final frame with all steps listed",
    ],
    platformFit: ["instagram", "youtube"],
  },
  {
    id:              "contrarian-take",
    name:            "Contrarian Bait",
    goal:            "High comment engagement via controversial angle",
    hookArchetype:   "controversial-take",
    visualStyle:     "talking-head-raw",
    narrativeArc:    "debate-contrast",
    tone:            "authoritative",
    energy:          "high",
    productionNotes: "Take a clear position. Back it with evidence. Invite disagreement. Controversy that is backed by logic = massive engagement.",
    thumbnailFormula:"Creator with strong expression. Quote from the contrarian take. Question mark or exclamation. Split opinion implied.",
    ctaFormula:      "Do you agree or disagree? Tell me exactly why in the comments",
    editingDirectives: [
      "Open with the controversial claim — no softening",
      "Present the mainstream view first, then dismantle it with evidence",
      "Use on-screen text to quote the 'wrong' advice being debunked",
      "End with your position restated with confidence",
      "Leave the question open enough to invite counter-arguments",
    ],
    platformFit: ["youtube", "instagram"],
  },
  {
    id:              "income-transparency",
    name:            "Income Transparency Report",
    goal:            "Viral trust + monetisation credibility signal",
    hookArchetype:   "confession",
    visualStyle:     "clean-minimal",
    narrativeArc:    "case-study",
    tone:            "vulnerable-personal",
    energy:          "calm",
    productionNotes: "Real numbers required. Don't sanitise — show the full picture including bad months. This format is viral because transparency is rare.",
    thumbnailFormula:"Exact figure on screen (e.g. 'Made £847 last month'). Creator face showing real emotion about it. Dark/serious tone.",
    ctaFormula:      "What's your honest monthly revenue right now? Comment below — no judgment",
    editingDirectives: [
      "Show actual screenshots of dashboards (blur only personal data)",
      "Month-by-month breakdown in a visual chart",
      "Narrate failures and low months with as much time as successes",
      "Use a consistent 'income report' template across all episodes for branding",
      "Chapters: This Month's Numbers → What Drove Growth → What Hurt → Next Month's Target",
    ],
    platformFit: ["youtube"],
  },
  {
    id:              "social-proof-stack",
    name:            "Social Proof Stack",
    goal:            "Convert viewers to followers via credibility signals",
    hookArchetype:   "social-proof",
    visualStyle:     "cinematic",
    narrativeArc:    "problem-solution",
    tone:            "educational-warm",
    energy:          "medium",
    productionNotes: "Results first. Let the outcomes speak. Stack testimonials, metrics, and before/afters. Cinematic feel adds production credibility.",
    thumbnailFormula:"Results number prominently displayed. Creator in professional setting. Warm, aspirational colour grade.",
    ctaFormula:      "Subscribe to join the community — I reply to every comment this week",
    editingDirectives: [
      "Open with the best result / most impressive testimonial",
      "Use slow-motion on the 'wow' moments",
      "Include at least 3 different proof sources: metric + testimonial + visual result",
      "Warm colour grade (+10 temp, +5 tint)",
      "Cinematic letter-boxing for the B-roll sections",
    ],
    platformFit: ["youtube", "instagram"],
  },
  {
    id:              "shock-stat-hook",
    name:            "Data Bomb",
    goal:            "High initial watch time via shocking opening statistic",
    hookArchetype:   "shock-stat",
    visualStyle:     "animation-driven",
    narrativeArc:    "revelation",
    tone:            "educational-warm",
    energy:          "high",
    productionNotes: "Open with a counterintuitive statistic. Visualise the data. Let the animation carry the explanation. No talking head needed for this one.",
    thumbnailFormula:"Large percentage / number on screen. Icon representing the topic. Clean, infographic feel.",
    ctaFormula:      "Which of these surprised you most? Let me know below",
    editingDirectives: [
      "Animated bar charts, pie charts, or counters for all statistics",
      "Upbeat background track at -15dB",
      "Text animates in as VO reads it — perfect timing is critical",
      "Source citations appear briefly on screen for credibility",
      "Kinetic text for the opening hook stat — must fill the screen",
    ],
    platformFit: ["youtube", "instagram"],
  },
  {
    id:              "fomo-carousel",
    name:            "FOMO Swipe",
    goal:            "High saves and swipe-through rate on Instagram carousels",
    hookArchetype:   "fomo",
    visualStyle:     "clean-minimal",
    narrativeArc:    "step-by-step",
    tone:            "hype",
    energy:          "high",
    productionNotes: "Each slide must deliver value AND create a reason to swipe to the next. Final slide = the payoff. Cover slide = must compel the swipe.",
    thumbnailFormula:"Cover slide: bold claim + swipe arrow. Numbered slides. Final slide: summary of all value delivered.",
    ctaFormula:      "Save this and share with someone who needs to see it",
    editingDirectives: [
      "Slide 1: The hook — bold, big, can't-miss-it",
      "Slides 2-9: One point per slide, clear and scannable",
      "Final slide: All points summarised + follow CTA",
      "Consistent brand colours across all slides",
      "Include a teaser on each slide about what's coming next",
    ],
    platformFit: ["instagram"],
  },
  {
    id:              "challenge-format",
    name:            "Challenge Starter",
    goal:            "Viral participation and user-generated content",
    hookArchetype:   "challenge",
    visualStyle:     "vlog-style",
    narrativeArc:    "transformation",
    tone:            "entertaining-fast",
    energy:          "explosive",
    productionNotes: "Lay out a specific, achievable challenge. Do it yourself on screen first. Invite the audience to post their attempt. Duet/collab angle maximises reach.",
    thumbnailFormula:"Creator mid-action. Challenge name prominent. 'Try This' or 'Can You...' framing.",
    ctaFormula:      "Try this and tag me — I repost every attempt I see",
    editingDirectives: [
      "Fast montage of the challenge being completed",
      "Clear rules displayed as on-screen text: 3 rules max",
      "Show a mistake / failed attempt before the success",
      "Use viral audio track that fits the challenge energy",
      "End with creator inviting the duet/stitch directly to camera",
    ],
    platformFit: ["instagram"],
  },
  {
    id:              "documentary-deep-dive",
    name:            "Documentary Deep Dive",
    goal:            "Watch time maximisation and subscriber conversion",
    hookArchetype:   "story-start",
    visualStyle:     "documentary",
    narrativeArc:    "case-study",
    tone:            "calm-expert",
    energy:          "calm",
    productionNotes: "Long form. Slow build. Let the story breathe. This format earns subscribers who stay. Average view duration > 50% is the target metric.",
    thumbnailFormula:"Atmospheric, cinematic shot. Minimal text. Intrigue over information. Dark, textured feel.",
    ctaFormula:      "If you made it to the end, subscribe — this is the kind of content I make",
    editingDirectives: [
      "Cold open: in medias res — start at the most interesting moment",
      "First-person narration over B-roll for the first 90 seconds",
      "Chapter markers every 5-7 minutes",
      "Ambient sound design under the whole video",
      "Let silences breathe — don't fill every moment with audio",
    ],
    platformFit: ["youtube"],
  },
  {
    id:              "question-answer",
    name:            "Direct Question Opener",
    goal:            "High comment velocity via community-centred format",
    hookArchetype:   "direct-question",
    visualStyle:     "talking-head-raw",
    narrativeArc:    "problem-solution",
    tone:            "educational-warm",
    energy:          "medium",
    productionNotes: "Open with their question, not your answer. Position as a community member, not a lecturer. Real-question submissions from comments = viral.",
    thumbnailFormula:"The question on screen in large text. Creator pointing at it or reacting to it.",
    ctaFormula:      "What's your question? Drop it below and I'll answer it in the next video",
    editingDirectives: [
      "Show the original comment/question on screen",
      "Answer in one continuous take if possible — authenticity over polish",
      "Side-by-side: question slide + creator responding",
      "Keep it under 8 minutes — questions deserve direct answers",
      "End with the next question teased from the comments",
    ],
    platformFit: ["youtube", "instagram"],
  },
];

// ── NANO BANANA ENGINE ────────────────────────────────────────────────────────

const LIBRARY_DIR  = join(process.cwd(), "intelligence", "content", ".nano-banana");
const LIBRARY_FILE = join(LIBRARY_DIR, "dna-library.json");
const MAX_LIBRARY  = 200; // Rolling window of recent content

export class NanaBananaEngine {
  private library: ContentDNA[] = [];
  private usageCounters: Map<string, number> = new Map();

  constructor() {
    this.ensureDir();
    this.loadLibrary();
  }

  // ── PUBLIC API ──────────────────────────────────────────────────────────────

  /**
   * Assigns a unique DNA fingerprint to a new piece of content.
   * Guarantees it is not too similar to any recent content.
   * Returns the DNA + enhancement recipe to use.
   */
  assignDNA(params: {
    contentId:  string;
    platform:   "instagram" | "youtube" | "both";
    topic:      string;
    preferRecipe?: string;  // Optional recipe hint (e.g. "viral-reel")
  }): { dna: ContentDNA; recipe: EnhancementRecipe } {

    const recipe = this.selectRecipe(params.platform, params.preferRecipe);
    const dna    = this.buildDNA(params.contentId, params.platform, params.topic, recipe);

    this.registerDNA(dna);

    return { dna, recipe };
  }

  /**
   * Enhances an InsForge or YouTubeForge package with Nano Banana directives.
   * Rewrites hook, thumbnail, CTA, and editing notes to match the assigned recipe.
   */
  enhanceHook(baseTopic: string, dna: ContentDNA, recipe: EnhancementRecipe): string {
    return this.craftHook(baseTopic, dna.hookArchetype);
  }

  enhanceCTA(dna: ContentDNA, recipe: EnhancementRecipe): string {
    return recipe.ctaFormula;
  }

  enhanceThumbnail(topic: string, recipe: EnhancementRecipe): string {
    return recipe.thumbnailFormula.replace(/\[topic\]/gi, topic);
  }

  enhanceEditingNotes(recipe: EnhancementRecipe): string {
    return [
      `[NANO BANANA — ${recipe.name.toUpperCase()}]`,
      `Goal: ${recipe.goal}`,
      `Visual style: ${recipe.visualStyle}`,
      `Energy: ${recipe.energy}`,
      ``,
      recipe.productionNotes,
      ``,
      "Production directives:",
      ...recipe.editingDirectives.map(d => `  • ${d}`),
    ].join("\n");
  }

  /**
   * Given a topic, returns whether a new content piece on that topic would
   * be too similar to recent content. Returns true if it's safe to proceed.
   */
  isNovelEnough(topic: string, platform: "instagram" | "youtube" | "both"): boolean {
    const recentTopics = this.library
      .filter(d => d.platform === platform || d.platform === "both" || platform === "both")
      .slice(-20)
      .map(d => d.topic.toLowerCase());

    const topicLower = topic.toLowerCase();
    const similarity = recentTopics.filter(t => this.stringSimilarity(topicLower, t) > 0.75).length;
    return similarity === 0;
  }

  /**
   * Returns a diversity report on the current content library.
   */
  diversityReport(): {
    totalPieces:       number;
    platformBreakdown: Record<string, number>;
    recipeUsage:       Record<string, number>;
    hookBreakdown:     Record<string, number>;
    noveltyAvg:        number;
    lastAssigned:      string;
  } {
    const byPlatform: Record<string, number> = {};
    const byRecipe:   Record<string, number> = {};
    const byHook:     Record<string, number> = {};
    let totalNovelty = 0;

    for (const d of this.library) {
      byPlatform[d.platform]      = (byPlatform[d.platform] ?? 0) + 1;
      byRecipe[d.recipeUsed]      = (byRecipe[d.recipeUsed] ?? 0) + 1;
      byHook[d.hookArchetype]     = (byHook[d.hookArchetype] ?? 0) + 1;
      totalNovelty += d.noveltyScore;
    }

    return {
      totalPieces:       this.library.length,
      platformBreakdown: byPlatform,
      recipeUsage:       byRecipe,
      hookBreakdown:     byHook,
      noveltyAvg:        this.library.length > 0 ? Math.round((totalNovelty / this.library.length) * 100) / 100 : 1,
      lastAssigned:      this.library.at(-1)?.generatedAt ?? "none",
    };
  }

  getAllRecipes(): EnhancementRecipe[] {
    return ENHANCEMENT_RECIPES;
  }

  getRecipe(id: string): EnhancementRecipe | undefined {
    return ENHANCEMENT_RECIPES.find(r => r.id === id);
  }

  // ── HOOK CRAFTING ───────────────────────────────────────────────────────────

  craftHook(topic: string, archetype: HookArchetype): string {
    const hooks: Record<HookArchetype, string[]> = {
      "curiosity-gap": [
        `Nobody tells you this about ${topic}...`,
        `The thing about ${topic} that everyone gets wrong`,
        `What they don't teach you about ${topic}`,
        `The part of ${topic} no one talks about`,
      ],
      "bold-claim": [
        `This one ${topic} change made all the difference`,
        `${topic} isn't what you think it is`,
        `Everything I thought I knew about ${topic} was wrong`,
        `This is the only ${topic} advice that actually works`,
      ],
      "story-start": [
        `6 months ago I knew nothing about ${topic}. Here's what changed.`,
        `I almost gave up on ${topic} — until this happened`,
        `The day I finally cracked ${topic}`,
        `This is the story of how ${topic} changed everything for me`,
      ],
      "direct-question": [
        `Are you making this ${topic} mistake right now?`,
        `How good is your ${topic} — honestly?`,
        `What's the one thing stopping you with ${topic}?`,
        `Do you actually understand ${topic}?`,
      ],
      "shock-stat": [
        `97% of people doing ${topic} are wasting their time`,
        `Most people who try ${topic} quit within 30 days. Here's why.`,
        `${topic} takes 10x longer without this`,
        `Only 3% of people know this about ${topic}`,
      ],
      "transformation": [
        `I went from 0 to [result] with ${topic} in 90 days`,
        `Before and after: what ${topic} actually does`,
        `This is what ${topic} looks like when you do it right`,
        `My ${topic} transformation — unfiltered`,
      ],
      "challenge": [
        `Try this ${topic} method for 7 days and tell me what happens`,
        `I dare you to test this ${topic} approach`,
        `Do this ${topic} thing once and you'll never go back`,
        `The ${topic} challenge nobody is talking about`,
      ],
      "confession": [
        `I need to be honest about my ${topic} results`,
        `Real talk: here's what ${topic} actually looks like`,
        `I was doing ${topic} completely wrong for years`,
        `The ${topic} truth nobody wants to admit`,
      ],
      "tutorial-preview": [
        `In the next 60 seconds I'll show you exactly how to do ${topic}`,
        `Let me show you my exact ${topic} process — step by step`,
        `Here's the ${topic} method I use — watch until the end`,
        `This is the only ${topic} tutorial you'll ever need`,
      ],
      "controversial-take": [
        `Hot take: ${topic} is overrated and here's why`,
        `Everyone says to do ${topic} this way. I disagree.`,
        `Stop listening to the ${topic} advice you're getting`,
        `The ${topic} strategy everyone recommends is holding you back`,
      ],
      "social-proof": [
        `I've helped 1,000 people get results with ${topic} — here's how`,
        `What the top 1% do differently with ${topic}`,
        `This is the ${topic} method that's working for everyone right now`,
        `After testing ${topic} with 500 people, here's what we found`,
      ],
      "fomo": [
        `Before you post another video, you need to know this about ${topic}`,
        `If you're not doing ${topic} like this, you're already behind`,
        `The ${topic} window is closing — here's what to do now`,
        `Everyone who understood ${topic} first is winning right now`,
      ],
    };

    const pool = hooks[archetype] ?? hooks["curiosity-gap"];
    return pool[Math.floor(Math.random() * pool.length)];
  }

  // ── PRIVATE METHODS ─────────────────────────────────────────────────────────

  private selectRecipe(
    platform: "instagram" | "youtube" | "both",
    preferRecipeId?: string
  ): EnhancementRecipe {
    if (preferRecipeId) {
      const preferred = ENHANCEMENT_RECIPES.find(r => r.id === preferRecipeId);
      if (preferred) return preferred;
    }

    // Filter by platform fit
    const eligible = ENHANCEMENT_RECIPES.filter(r =>
      platform === "both" || r.platformFit.includes(platform)
    );

    // Pick the least recently used recipe
    const sortedByUsage = eligible
      .map(r => ({ recipe: r, uses: this.usageCounters.get(r.id) ?? 0 }))
      .sort((a, b) => a.uses - b.uses);

    return sortedByUsage[0].recipe;
  }

  private buildDNA(
    contentId: string,
    platform: "instagram" | "youtube" | "both",
    topic: string,
    recipe: EnhancementRecipe
  ): ContentDNA {
    // Find a combination novel enough relative to recent library
    const candidates = this.generateCandidates(recipe, platform);
    const best = this.pickMostNovel(candidates, topic);

    const fingerprint = this.generateFingerprint(best);

    return {
      fingerprint,
      hookArchetype:  best.hookArchetype,
      visualStyle:    best.visualStyle,
      narrativeArc:   best.narrativeArc,
      tone:           best.tone,
      energy:         best.energy,
      recipeUsed:     recipe.id,
      noveltyScore:   best.noveltyScore,
      generatedAt:    new Date().toISOString(),
      contentId,
      platform,
      topic,
    };
  }

  private generateCandidates(
    recipe: EnhancementRecipe,
    platform: "instagram" | "youtube" | "both"
  ): Array<{
    hookArchetype: HookArchetype;
    visualStyle:   VisualStyle;
    narrativeArc:  NarrativeArc;
    tone:          Tone;
    energy:        EnergyLevel;
    noveltyScore:  number;
  }> {
    const candidates = [];

    // Generate 8 candidates mixing the recipe's primary axes with rotated alternatives
    for (let i = 0; i < 8; i++) {
      const hookIdx   = (HOOK_ARCHETYPES.indexOf(recipe.hookArchetype) + i) % HOOK_ARCHETYPES.length;
      const visualIdx = (VISUAL_STYLES.indexOf(recipe.visualStyle) + Math.floor(i / 2)) % VISUAL_STYLES.length;
      const arcIdx    = (NARRATIVE_ARCS.indexOf(recipe.narrativeArc) + Math.floor(i / 3)) % NARRATIVE_ARCS.length;
      const toneIdx   = (TONES.indexOf(recipe.tone) + Math.floor(i / 4)) % TONES.length;
      const energyIdx = (ENERGY_LEVELS.indexOf(recipe.energy) + Math.floor(i / 5)) % ENERGY_LEVELS.length;

      candidates.push({
        hookArchetype: HOOK_ARCHETYPES[hookIdx],
        visualStyle:   VISUAL_STYLES[visualIdx],
        narrativeArc:  NARRATIVE_ARCS[arcIdx],
        tone:          TONES[toneIdx],
        energy:        ENERGY_LEVELS[energyIdx],
        noveltyScore:  0,
      });
    }

    return candidates;
  }

  private pickMostNovel(
    candidates: Array<{
      hookArchetype: HookArchetype;
      visualStyle:   VisualStyle;
      narrativeArc:  NarrativeArc;
      tone:          Tone;
      energy:        EnergyLevel;
      noveltyScore:  number;
    }>,
    topic: string
  ) {
    const recentFingerprints = this.library.slice(-30).map(d => d.fingerprint);

    let best = candidates[0];
    let bestNovelty = -1;

    for (const c of candidates) {
      const fp = `${c.hookArchetype}|${c.visualStyle}|${c.narrativeArc}|${c.tone}|${c.energy}`;
      const similarity = recentFingerprints.filter(r => r === fp).length;
      const novelty = 1 - (similarity / Math.max(1, recentFingerprints.length));
      c.noveltyScore = Math.round(novelty * 100) / 100;

      if (c.noveltyScore > bestNovelty) {
        bestNovelty = c.noveltyScore;
        best = c;
      }
    }

    return best;
  }

  private generateFingerprint(axes: {
    hookArchetype: HookArchetype;
    visualStyle:   VisualStyle;
    narrativeArc:  NarrativeArc;
    tone:          Tone;
    energy:        EnergyLevel;
  }): string {
    return `${axes.hookArchetype}|${axes.visualStyle}|${axes.narrativeArc}|${axes.tone}|${axes.energy}`;
  }

  private registerDNA(dna: ContentDNA): void {
    this.library.push(dna);
    this.usageCounters.set(dna.recipeUsed, (this.usageCounters.get(dna.recipeUsed) ?? 0) + 1);

    // Keep rolling window
    if (this.library.length > MAX_LIBRARY) {
      this.library = this.library.slice(-MAX_LIBRARY);
    }

    this.persistLibrary();
  }

  /** Simple bigram-based string similarity for topic deduplication */
  private stringSimilarity(a: string, b: string): number {
    const getBigrams = (s: string) => {
      const bigrams = new Set<string>();
      for (let i = 0; i < s.length - 1; i++) bigrams.add(s.slice(i, i + 2));
      return bigrams;
    };
    const bigramsA = getBigrams(a);
    const bigramsB = getBigrams(b);
    const intersection = [...bigramsA].filter(bg => bigramsB.has(bg)).length;
    return (2.0 * intersection) / (bigramsA.size + bigramsB.size);
  }

  private ensureDir(): void {
    if (!existsSync(LIBRARY_DIR)) mkdirSync(LIBRARY_DIR, { recursive: true });
  }

  private loadLibrary(): void {
    try {
      if (existsSync(LIBRARY_FILE)) {
        const data = JSON.parse(readFileSync(LIBRARY_FILE, "utf-8")) as { library: ContentDNA[] };
        this.library = data.library ?? [];
        for (const d of this.library) {
          this.usageCounters.set(d.recipeUsed, (this.usageCounters.get(d.recipeUsed) ?? 0) + 1);
        }
      }
    } catch { /* start fresh */ }
  }

  private persistLibrary(): void {
    try {
      writeFileSync(LIBRARY_FILE, JSON.stringify({ library: this.library, updatedAt: new Date().toISOString() }, null, 2), "utf-8");
    } catch { /* non-fatal */ }
  }
}

export const nanaBanana = new NanaBananaEngine();
export default nanaBanana;
